# Use postgres/example user/password credentials
version: '3.1'
services:

  adminer:
    image: adminer
    restart: always
    ports: 
      - '8000:8080'    
  postgresdb:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password